### PR TITLE
Added read the doc page and files referred by the documentation

### PR DESCRIPTION
**Pull request by schandrika**
In addition to providing useful description, please ensure the following:

- [x] If merging to main, bump the version in the galaxy.yml file

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron-ansible/9)

### CODE REVIEW

**Comment by laroque** [comment]
The recipes subdir is redundant with root of the repo and should probably just be dropped (this repo has had chances not included in VOLTTRON/volttron). That may break one or more links when generating the docs by parsing the variables yaml file.

**Comment by schandrika** [comment]
@laroque I have moved files one level up.

**Comment by laroque** [comment]
the `library` dir was also moved to `plugins/modules` and the top-level `templates` dir's contents were moved into their corresponding roles `roles/<some-role>/templates`

**Comment by craig8** [comment]
running make html from the docs folder after bootstrapping using python3 bootstrap.py --documentation gives the following error;

````
Running Sphinx v3.2.1

Extension error:
Could not import extension sphinxcontrib.autoyaml (exception: No module named 'sphinxcontrib.autoyaml')
make: *** [Makefile:19: html] Error 2
````

We should update the --documentation tree to install this package.

Can we make sure the requirements.txt in this repo are in the --documentation tree?

**Comment by craig8** [comment]
Please fix the auto yaml errors

````
Running Sphinx v3.2.1
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
/home/os2004/repos/volttron-ansible/docs/source/index.rst:323: WARNING: malformed hyperlink target.

AutoYAML error:
index.rst:344: location "/home/os2004/repos/volttron-ansible/roles/set-defaults/tasks/main.yml" is not a file.
make: *** [Makefile:19: html] Error 2
````

**Comment by craig8** [comment]
Can we get rid of the warnings here...perhaps then we can do the same from our main repo and make the whole thing better

````
Running Sphinx v3.2.1
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
/home/os2004/repos/volttron-ansible/docs/source/index.rst:323: WARNING: malformed hyperlink target.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
/home/os2004/repos/volttron-ansible/docs/source/index.rst:22: WARNING: undefined label: bootstrap-options (if the link has no caption the label must precede a section header)
/home/os2004/repos/volttron-ansible/docs/source/index.rst:28: WARNING: undefined label: recipes-configuration (if the link has no caption the label must precede a section header)
/home/os2004/repos/volttron-ansible/docs/source/index.rst:51: WARNING: undefined label: recipe-example (if the link has no caption the label must precede a section header)
/home/os2004/repos/volttron-ansible/docs/source/index.rst:209: WARNING: undefined label: recipes-configuration (if the link has no caption the label must precede a section header)
````

**Comment by craig8** [comment]
Can we apply the same theme modifications that we have in the main repo.  Eventually we may have an additional thing that allows these repos to be seamless between them as far as rtd is concerned.

image

**Comment by craig8** [comment]
I am going to approve this and merge it so we can get it going into the sub-project for volttron.

**Pull request merged**
